name: simple_auth
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  auto_route: ^7.1.0
  auto_route_generator: ^7.0.0
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.2
  connectivity_plus: ^4.0.1
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_secure_storage: ^8.0.0
  flutter_svg: ^2.0.5
  freezed_annotation: ^2.2.0
  gap: ^3.0.1
  get_it: ^7.3.0
  http: ^1.0.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  lint: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
